### ISSUE TITLE
custom config file removed after first use

### ISSUE THREAD

**Issue by marekorok** [Sabuto/hassio-telegraf#26]
Hi,
#Description of issue

I wanted to implement collectd input plugin for telegraf so I wrote custom file.
I took me a while to realize, that with custom_conf enabled I need full telegraf.conf file, with all options, but it's fine, perhaps worth to mention in docs.

Unfortunately found issue: after first use seems the file is **moved** from /share/telegraf.conf to /etc/telegraf/telegraf.conf. In result after hassio, plugin or docker restart it fails to start and complains for missing file, as below.

# Logs
[21:37:07] INFO: Using custom conf file
mv: cannot stat '/share/telegraf.conf': No such file or directory

**Comment by Sabuto** [comment]
this relates to [issue](https://github.com/Sabuto/hassio-repo/issues/6)

**Comment by Sabuto** [comment]
0.5.4 should fix this :)
