### ISSUE TITLE
depreciated errors

### ISSUE THREAD

**Issue by optikkore** [Sabuto/hassio-telegraf#34]
#Type of Issue
<!--- Is this a feature request or an issue? ---!>

#Description of issue
21-02-25 13:31:01 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Telegraf
21-02-25 13:31:01 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Jackett

#Ideas to fix
<!--- if you have nay ideas to fix this issue please specify them here ---!>

# Logs
21-02-25 13:31:01 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Telegraf
21-02-25 13:31:01 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Jackett

**Comment by Sabuto** [comment]
Thanks for this, i'll update when i get chance, atleast its deprecated and not working atm

**Comment by Sabuto** [comment]
This should now be fixed with version 0.5.7 :)
