### ISSUE TITLE
Update to 0.5.7 version causes all other add-ons fail and supervior gives error that I run unsupported version. 

### ISSUE THREAD

**Issue by przemo** [Sabuto/hassio-telegraf#36]
I can’t provide the logs, since I have no idea where they are located for an add on. 
I experienced that issue two times, after restoring home assistant form a backup. Generally, when I updated the Telegraf add on, the HA is restarted but all other addons fail to start. In supervisor I get an error message that I run unsupported version. I am not sure if this is due to conflicts with other configuration, but after restoring Hassio I tried to updated the Telegraf again and this thing happened one more time. I removed the Telegraf Addon, and restarted HA, but it is not booting back. Need to do recovery again. I used the earlier version of the Telegraf and everything was fine. 
I wish I could provide more info, but at the moment I will refrain from using this add-on. 
If you have any suggestions how I can provider more info it would be great.

**Comment by Sabuto** [comment]
Hi,

Sorry this is happening, someone else had a similar problem before but i can't find how they resolved it. I will do some research and get back to you :)

**Comment by gaetan-p** [comment]
Hi,
Same problem here, my homeassistant crashed and is not http-reachable anymore. I now only have access on CLI with screen attached. How can I stop/remove the telegraf addon via CLI please ?

**Comment by alceasan** [comment]
Same here, I also tried to stop it using the Portainer addon with the same result: instantly lose access to ha core and other plugins like ssh. Hard reset to get it back.

**Comment by Sabuto** [comment]
ok i will undo the changes i made in this version to get this to a working state with deprecation warnings

**Comment by SNoof85** [comment]
I have this also. On top of that it crashed the update of HAOS to 6.0. I disabled the addon and it worked.

**Comment by Sabuto** [comment]
I will try services. I will do some testing. If not I may have to re-write the plugin going through the new docs

**Comment by gaetan-p** [comment]
FYI, since I've disabled the auto-start on boot, it works just fine on my installation.
I just start it manually in case I reboot my host. That's kind of fine with me :)

**Comment by Sabuto** [comment]
Ok so if your host system is up and it's the last thing you spin up it works?On 15 Jun 2021 9:02 am, Gaetan ***@***.***> wrote:
FYI, since I've disabled the auto-start on boot, it works just fine on my installation.
I just start it manually in case I reboot my host. That's kind of fine with me :)

**Comment by gaetan-p** [comment]
Yes, I confirm if my host is up and I start it manually (so more or less last) it works (with last stable HA available)
Now maybe hopefully others will confirm this as my installation is quite minimal and simple.

**Comment by Sabuto** [comment]
> 
> 
> Yes, I confirm if my host is up and I start it manually (so more or less last) it works (with last stable HA available)
> Now maybe hopefully others will confirm this as my installation is quite minimal and simple.

@SNoof85 @alceasan @przemo can you guys confirm? The strange thing is from what i can see 'Application' should start once everything else has

**Comment by SNoof85** [comment]
Will try it when at home. Don't want to remote kill everything 🤣

**Comment by Sabuto** [comment]
hmm ok, when i first built this plugin i didnt understand s6, but as that is now the default for HA addons i am going to redo it and include that (it handles errors a lot better, i will also update the Telegraf version)

**Comment by SNoof85** [comment]
If tester needed don't hesitate 🚀

**Comment by SNoof85** [comment]
My instance is HAOS on a proxmox VM (using the home assistant qemu image)

## System Health

version | core-2021.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.42
arch | x86_64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.12.4
Stage | running
Available Repositories | 851
Installed Repositories | 20

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.0
docker_version | 20.10.6
disk_total | 19.0 GB
disk_used | 6.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Node-RED (9.1.4), File editor (5.3.1), Check Home Assistant configuration (3.7.1), RPC Shutdown (2.2), Mosquitto broker (6.0.1), Terminal & SSH (9.1.3), Samba Backup (4.5.0), Portainer (1.5.1), Z-Wave JS (0.1.25), Zigbee2mqtt (1.18.1-1), Telegraf (0.5.7)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 19
views | 13
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by alceasan** [comment]
I can also test, my platform is Home Assistant OS on RPi4 (arm64).

**Comment by gaetan-p** [comment]
I am running it on a RPI3.

![image](https://user-images.githubusercontent.com/30925906/122201465-57e86480-ce9c-11eb-9eb6-478bcbdc4a2d.png)

**Comment by LilTrublMakr** [comment]
Starting the addon manually makes it work for a few minutes and then restarts the virtual machine for me. It may be something different issue wise though.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07:37:21] INFO: Using custom conf file
cp: cannot stat '/root/config/telegraf/telegraf.conf': No such file or directory
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

I tried again without using the custom config, and I manually stopped the ~~container~~ plug-in and it restarted my VM as well.

**Comment by Sabuto** [comment]
Ok so i have tried downgrading back to how it was with the deprecation errors and it is crashing my docker every time i stiop the container. I think there must be an update with home assistant itself and how it processes things

**Comment by SNoof85** [comment]
Well, it's easy to reproduce the issue but finding clues looks hard.
Maybe it worth speaking with HA experts on discord...

**Comment by Sabuto** [comment]
> 
> 
> Well, it's easy to reproduce the issue but finding clues looks hard.
> Maybe it worth speaking with HA experts on discord...

already on that ;)

**Comment by Sabuto** [comment]
Ok i have updated the container, and pushed to https://github.com/Sabuto/hassio-telegraf/tree/major/update-to-new-dev, I have included the .devcontainer and .vscode folders for easy local dev. It is working on my end but if you guys could test it too that would be great. Once i have some confirmation i will merge with the main branch.

**Comment by SNoof85** [comment]
Will check on an easy way to test it. At the moment no idea 🤣 
If you have any easy solution

**Comment by Sabuto** [comment]
clone the repo, checkout the branch (have docker, wsl 2 (if on windows) installed on computer). open folder in vscode and reopen in container then run task start home assistant. If this is too hard for people i may just push it to the main branch as it's not working properly atm anyway

**Comment by SNoof85** [comment]
Will try with local dev env. Not yet in testing env i have (2nd VM of HAOS for testing) and will report.
Thing is that i would love to try it out on real conditions but anyway local dev should give an idea !

**Comment by Sabuto** [comment]
tell you what if i can get one person, to confirm it work's locally other than me i will push to main branch with a warning about updating until it has been tested

**Comment by SNoof85** [comment]
Sure i can test it locally, currently facing docker issue when starting home assistant...dunno why exactly but i can fix it, keep faith !
Will report ASAP 👍

**Comment by Sabuto** [comment]
> 
> 
> Sure i can test it locally, currently facing docker issue when starting home assistant...dunno why exactly but i can fix it, keep faith !
> Will report ASAP 👍

haha, yeah i had a p[roblem too, does it grumble about nat tables or something?

**Comment by SNoof85** [comment]
was something about network create. Error 500... Updated everything (slow internet here).
It's building up the dev container now...

**Comment by Sabuto** [comment]
ok cool, if it does complain about iptables do this command in wsl2, iptables -t nat -N DOCKER

**Comment by SNoof85** [comment]
Now i have the iptables thing. Aaaand your command doesn't looks like to get it better at the moment. Having a break, i'll think better when feeded 🤣

**Comment by SNoof85** [comment]
OK then now i've been able to test :)

The addon is not starting... 
```
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] telegraf.sh: executing... 
exec: fatal: unable to exec bashio
: No such file or directory
[cont-init.d] telegraf.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
/usr/bin/env: 'bash\r': No such file or directory
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by Sabuto** [comment]
> exec: fatal: unable to exec bashio

this is because it has converted to windows line ending's

https://community.home-assistant.io/t/exec-fatal-unable-to-exec-bashio-no-such-file-or-directory/214752

**Comment by Sabuto** [comment]
also try adding this repo to one of your test instances :) https://github.com/Sabuto/hassio-repo-dev

**Comment by SNoof85** [comment]
OK then test with local env works good 👍 
Testing on latest HAOS on proxmox...

**Comment by LilTrublMakr** [comment]
I can also confirm that the test build it starting and stopping without HA crashing.

**Comment by Sabuto** [comment]
Perfect, I'll push to the main repo and you'll see an update soon :)

**Comment by przemo** [comment]
Thanks!
