### ISSUE TITLE
Configure input and output

### ISSUE THREAD

**Issue by jli113** [sabuto/hassio-telegraf#44]
#Type of Issue
<!--- Is this a feature request or an issue? ---!>
Feature request
#Description of issue
All the inputs and outputs are listed in the same column, not easy to set inputs and outputs.

#Ideas to fix
<!--- if you have nay ideas to fix this issue please specify them here ---!>
Configure input and output

# Logs
<!--- please past the logs here ---!>

**Comment by sabuto** [comment]
do you meant to have an inputs: and outputs: section within the config?

**Comment by jli113** [comment]
That would be great.

**Comment by sabuto** [comment]
the only thing with that for me would be that i havent enabled all the available inputs and outputs for telegraf, so this would seem redundant, i mean you can put them in any order you would like so you could put your inputs at the top and the outputs at the bottom?

**Comment by jli113** [comment]
So the only output available for now is influxdb, the others are all inputs that can be any order?

**Comment by sabuto** [comment]
correct, if you would like to use your own config file that is available where you can specify all of the inputs and output available to telegraf

**Comment by jli113** [comment]
Do you mean this "/share/telegraf.conf" file?
![image](https://user-images.githubusercontent.com/33822210/154219982-7cdf4146-6f84-41bf-831c-e13ebaa11f54.png)
Do I need to create this file and follow the telegraf configuration file format?

**Comment by sabuto** [comment]
yes, if you manually create it and store it in your share folder hassio-telegraf will pick it up :)

**Comment by jli113** [comment]
In that case, does it support other outputs?

**Comment by sabuto** [comment]
yes with a custom config file it will support anything just bear in mind atm it is running 1.17.3 i am working on updating it but im trying to streamline with the community addons

**Comment by jli113** [comment]
After creating /share/telegraf.conf, it's still using the default configuration. Instead of using the file I created, it's using /etc/telegraf/telegraf.conf.

**Comment by sabuto** [comment]
did you update the config to specify you want to use a custom config?

**Comment by jli113** [comment]
Thanks, forgot that.
