### ISSUE TITLE
Can't run the service?

### ISSUE THREAD

**Issue by JHenzi** [Sabuto/hassio-telegraf#6]
The logs showed this; 

[09:10:34] INFO: Updating config
[09:10:38] INFO: Finished updating config, Starting Telegraf
/run.sh: line 56: /usr/bin/telegraf: cannot execute binary file: Exec format error

**Comment by Sabuto** [comment]
What version are you running?, what version of home assistant are you running? What are you running home assistant on?

**Comment by JHenzi** [comment]
Home Assistant 0.101.2
Telegraf 0.3.1 

Running on a PI 2, just getting started before I sacrifice a PI 3 to this.

**Comment by Sabuto** [comment]
thanks, I am working on it now a new release should be up tonight. can you install influxdb on your pi?

**Comment by Sabuto** [comment]
Please update to 0.4.0 this should fix the issue.

**Comment by JHenzi** [comment]
Thanks Sabuto, I am running Influx on the same. 

Side question: Was curious on sending the data to another machine but it is only accepting requests by IP and not using authentication. When I take this out of the config it throws an error. Must I run telegraf in hass.io as an authenticated user against influx?

**Comment by Sabuto** [comment]
@JHenzi sorry only just saw this, please open an issue and I will look into this. If not unwilling open an issue when I get round to it :)
